def calculate_inverse(number):
    assert (number != 0), "Got 0 as number!"
    return 1/number

calculate_inverse(5)
calculate_inverse(0) #Causes Assertion Error